### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [2]:
# Dependencies and Setup
import pandas as pd

# File to Load (Remember to Change These)
file_to_load = "Resources/purchase_data.csv"

# Read Purchasing File and store into Pandas data frame
purchase_data = pd.read_csv(file_to_load)
purchase_data.head()

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56
2,2,Ithergue48,24,Male,92,Final Critic,4.88
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27
4,4,Iskosia90,23,Male,131,Fury,1.44

## Player Count

* Display the total number of players

In [4]:
#total number of players 
player_count_df = pd.DataFrame({
    "Total Players":[len(purchase_data['SN'].unique())]
})
player_count_df

   Total Players
0            576

## Purchasing Analysis (Total)

* Run basic calculations to obtain number of unique items, average price, etc.


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [5]:
purchases_df = pd.DataFrame({
    "Number of Unique Items":[len(purchase_data['Item ID'].unique())],
    "Average Purchase Price":[round(purchase_data['Price'].mean(),2)],
    "Total Number of Purchases":[purchase_data['Purchase ID'].count()],
    "Total Revenue":[purchase_data['Price'].sum()]
})

purchases_df

,Number of Unique Items,Average Purchase Price,Total Number of Purchases,Total Revenue
0,183,3.05,780,2379.77

## Gender Demographics

In [9]:
#purchases by gender
purchase_data.groupby('Gender')['Purchase ID'].count()

Gender
Female                   113
Male                     652
Other / Non-Disclosed     15
Name: Purchase ID, dtype: int64

In [9]:
#unique purchasers
len(purchase_data['SN'].unique())

576

In [10]:
#percentage and count of male, female, and other players
user_list = purchase_data.drop_duplicates(subset = 'SN')
gender_df = user_list['Gender'].value_counts()
for i in range(len(gender_df)):
    print("{}: {}, %: {} \n".format(gender_df.index[i], gender_df[i], round(gender_df[i]/gender_df.sum()*100,2)))

Male: 484, %: 84.03

Female: 81, %: 14.06

Other / Non-Disclosed: 11, %: 1.91

* Percentage and Count of Male Players


* Percentage and Count of Female Players


* Percentage and Count of Other / Non-Disclosed


## Purchasing Analysis (Gender)

In [10]:
#purchase count by gender
purchase_data.groupby('Gender')['Purchase ID'].count()

Gender
Female                   113
Male                     652
Other / Non-Disclosed     15
Name: Purchase ID, dtype: int64

In [12]:
#average purchase price by gender
round(purchase_data.groupby('Gender')['Price'].mean(),2)

Gender
Female                   3.20
Male                     3.02
Other / Non-Disclosed    3.35
Name: Price, dtype: float64

In [13]:
#toal purchase value by gender
purchase_data.groupby('Gender')['Price'].sum()

Gender
Female                    361.94
Male                     1967.64
Other / Non-Disclosed      50.19
Name: Price, dtype: float64

In [29]:
#average purchase total per person by gender
#i take this as the averages of all purchases by each man, woman, and other
gender_data = purchase_data.groupby(['Gender','SN'])['Price'].sum()
#gender_data

In [49]:
averages_gender=gender_data.groupby('Gender').mean()
averages_gender

Gender
Female                   4.468395
Male                     4.065372
Other / Non-Disclosed    4.562727
Name: Price, dtype: float64

* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. by gender




* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

In [31]:
purchase_data['Age'].max()

45

## Age Demographics

* Establish bins for ages


* Categorize the existing players using the age bins. Hint: use pd.cut()


* Calculate the numbers and percentages by age group


* Create a summary data frame to hold the results


* Optional: round the percentage column to two decimal points


* Display Age Demographics Table

In [35]:
bins = [0,9,14,19,24,29,34,39,44,99]
bin_names = ['<10', '10-14', '15-19', '20-24', '25-29', '30-34', '35-39', '40-44', '>44']

purchase_data['Age Group'] = pd.cut(purchase_data['Age'], bins, labels=bin_names)
purchase_data

,Purchase ID,SN,Age,Gender,Item ID,Item Name,Price,Age Group
0,0,Lisim78,20,Male,108,"Extraction, Quickblade Of Trembling Hands",3.53,20-24
1,1,Lisovynya38,40,Male,143,Frenzied Scimitar,1.56,40-44
2,2,Ithergue48,24,Male,92,Final Critic,4.88,20-24
3,3,Chamassasya86,24,Male,100,Blindscythe,3.27,20-24
4,4,Iskosia90,23,Male,131,Fury,1.44,20-24
5,5,Yalae81,22,Male,81,Dreamkiss,3.61,20-24
6,6,Itheria73,36,Male,169,"Interrogator, Blood Blade of the Queen",2.18,35-39
7,7,Iskjaskst81,20,Male,162,Abyssal Shard,2.67,20-24
8,8,Undjask33,22,Male,21,Souleater,1.10,20-24
9,9,Chanosian48,35,Other / Non-Disclosed,136,Ghastly Adamantite Protector,3.58,35-39
10,10,Inguron55,23,Male,95,Singed Onyx Warscythe,4.74,20-24
11,11,Haisrisuir60,23,Male,162,Abyssal Shard,2.67,20-24
12,12,Saelaephos52,21,Male,116,Renewed Skeletal Katana,4.18,20-24
13,13,Assjaskan73,22,Male,4,Bloodlord's Fetish,1.70,20-24
14,14,Saesrideu94,35,Male,165,Bone Crushing Silver Skewer,4.86,35-39
15,15,Lisassa64,21,Female,98,"Deadline, Voice Of Subtlety",2.89,20-24
16,16,Lisirra25,20,Male,40,Second Chance,2.52,20-24
17,17,Zontibe81,21,Male,161,Devine,1.76,20-24
18,18,Reunasu60,22,Female,82,Nirvana,4.90,20-24
19,19,Chamalo71,30,Male,89,"Blazefury, Protector of Delusions",4.64,30-34
20,20,Iathenudil29,20,Male,57,"Despair, Favor of Due Diligence",4.60,20-24
21,21,Phiarithdeu40,20,Male,168,"Sun Strike, Jaws of Twisted Visions",1.48,20-24
22,22,Siarithria38,38,Other / Non-Disclosed,24,Warped Fetish,3.81,35-39
23,23,Eyrian71,40,Male,151,Severance,3.40,40-44
24,24,Siala43,30,Male,141,Persuasion,3.19,30-34
25,25,Lisirra87,29,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,25-29
26,26,Lirtossa84,11,Male,71,Demise,1.61,10-14
27,27,Eusri44,7,Male,96,Blood-Forged Skeletal Spine,3.09,<10
28,28,Aela59,21,Male,119,"Stormbringer, Dark Blade of Ending Misery",4.32,20-24
29,29,Tyida79,24,Male,37,"Shadow Strike, Glory of Ending Hope",3.16,20-24
...,...,...,...,...,...,...,...,...
750,750,Iljask75,22,Male,167,"Malice, Legacy of the Queen",3.61,20-24
751,751,Lisjaskan36,11,Male,180,Stormcaller,3.36,10-14
752,752,Mindjasksya61,17,Male,112,Worldbreaker,2.60,15-19
753,753,Frichirranya75,36,Male,178,"Oathbreaker, Last Hope of the Breaking Storm",4.23,35-39
754,754,Pheosurllorin41,23,Female,79,"Alpha, Oath of Zeal",4.05,20-24
755,755,Raesty92,12,Male,76,Haunted Bronzed Bludgeon,3.15,10-14
756,756,Ilast79,20,Male,73,Ritual Mace,2.05,20-24
757,757,Eratiel90,18,Male,57,"Despair, Favor of Due Diligence",4.60,15-19
758,758,Iral74,21,Male,182,Toothpick,4.03,20-24
759,759,Tyaelorap29,25,Male,72,Winter's Bite,3.77,25-29
760,760,Aithelis62,21,Male,44,Bonecarvin Battle Axe,2.38,20-24
761,761,Assim27,45,Male,17,"Lazarus, Terror of the Earth",1.70,>44
762,762,Asur53,26,Male,110,Suspension,1.44,25-29
763,763,Lassilsala30,21,Male,85,Malificent Bag,1.75,20-24
764,764,Saedaiphos46,18,Male,113,Solitude's Reaver,4.07,15-19
765,765,Irith83,18,Male,130,Alpha,2.07,15-19
766,766,Aelastirin39,23,Male,58,"Freak's Bite, Favor of Holy Might",4.14,20-24
767,767,Ilmol66,8,Female,92,Final Critic,4.88,<10
768,768,Assassasta79,38,Male,92,Final Critic,4.88,35-39
769,769,Ilosian36,15,Male,145,Fiery Glass Crusader,4.58,15-19
770,770,Lirtosia63,34,Male,12,Dawne,1.02,30-34
771,771,Iskossasda43,16,Male,25,Hero Cane,4.35,15-19
772,772,Asur53,26,Male,136,Ghastly Adamantite Protector,3.58,25-29
773,773,Hala31,21,Male,19,"Pursuit, Cudgel of Necromancy",1.02,20-24
774,774,Jiskjask80,11,Male,101,Final Critic,4.19,10-14
775,775,Aethedru70,21,Female,60,Wolf,3.54,20-24
776,776,Iral74,21,Male,164,Exiled Doomblade,1.63,20-24
777,777,Yathecal72,20,Male,67,"Celeste, Incarnation of the Corrupted",3.46,20-24
778,778,Sisur91,7,Male,101,Final Critic,4.19,<10
779,779,Ennrian78,24,Male,50,Dawn,4.60,20-24

In [41]:
#purchase count
purchase_data.groupby('Age Group')['Purchase ID'].count()

Age Group
<10       23
10-14     28
15-19    136
20-24    365
25-29    101
30-34     73
35-39     41
40-44     12
>44        1
Name: Purchase ID, dtype: int64

In [44]:
#average purchase price
round(purchase_data.groupby('Age Group')['Price'].mean(),2)

Age Group
<10      3.35
10-14    2.96
15-19    3.04
20-24    3.05
25-29    2.90
30-34    2.93
35-39    3.60
40-44    3.04
>44      1.70
Name: Price, dtype: float64

In [45]:
#total purchase value
purchase_data.groupby('Age Group')['Price'].sum()

Age Group
<10        77.13
10-14      82.78
15-19     412.89
20-24    1114.06
25-29     293.00
30-34     214.00
35-39     147.67
40-44      36.54
>44         1.70
Name: Price, dtype: float64

In [50]:
#average purchase total per person by age group
#i take this as the average of all purchases by each person in each age group
age_data = purchase_data.groupby(['Age Group','SN'])['Price'].sum()
age_data.head()

Age Group  SN
<10        Anallorgue57    5.70
           Chadjask77      4.93
           Chanossast57    4.32
           Eurithphos97    4.55
           Eusri44         3.09
Name: Price, dtype: float64

In [52]:
averages_age = age_data.groupby('Age Group').mean()
averages_age

Age Group
<10      4.537059
10-14    3.762727
15-19    3.858785
20-24    4.318062
25-29    3.805195
30-34    4.115385
35-39    4.763548
40-44    3.321818
>44      1.700000
Name: Price, dtype: float64

## Purchasing Analysis (Age)

* Bin the purchase_data data frame by age


* Run basic calculations to obtain purchase count, avg. purchase price, avg. purchase total per person etc. in the table below


* Create a summary data frame to hold the results


* Optional: give the displayed data cleaner formatting


* Display the summary data frame

## Top Spenders

* Run basic calculations to obtain the results in the table below


* Create a summary data frame to hold the results


* Sort the total purchase value column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [121]:
#identify top 5 spenders by total purchase value, 
#list SN, purchase count, averae purchase price, and total purchase value
spenders = purchase_data.groupby('SN')['Price'].sum()
spenders=spenders.sort_values(ascending=False).head()
spenders

#for each spender, display name, purchase count, avg price, and total value
for i in range(len(spenders)):
    print("SN: {} // Purchase Count: {} // Avg Purchase Price: ${} // Revenue: ${}".format(
        spenders.index[i],
        purchase_data.loc[purchase_data['SN'] == spenders.index[i]]['Purchase ID'].count(),
        round(purchase_data.loc[purchase_data['SN'] == spenders.index[i]]['Price'].mean(),2),
        round(purchase_data.loc[purchase_data['SN'] == spenders.index[i]]['Price'].sum(),2)))

SN: Lisosia93 // Purchase Count: 5 // Avg Purchase Price: $3.79 // Revenue: $18.96
SN: Idastidru52 // Purchase Count: 4 // Avg Purchase Price: $3.86 // Revenue: $15.45
SN: Chamjask73 // Purchase Count: 3 // Avg Purchase Price: $4.61 // Revenue: $13.83
SN: Iral74 // Purchase Count: 4 // Avg Purchase Price: $3.4 // Revenue: $13.62
SN: Iskadarya95 // Purchase Count: 3 // Avg Purchase Price: $4.37 // Revenue: $13.1

## Most Popular Items

* Retrieve the Item ID, Item Name, and Item Price columns


* Group by Item ID and Item Name. Perform calculations to obtain purchase count, item price, and total purchase value


* Create a summary data frame to hold the results


* Sort the purchase count column in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the summary data frame

In [113]:
#most popular items by purchase count
items_sold = purchase_data.groupby('Item ID')['Item ID'].count()
items_sold = items_sold.sort_values(ascending=False).head()
items_sold

Item ID
178    12
82      9
108     9
145     9
92      8
Name: Item ID, dtype: int64

In [114]:
#purchase_data.loc[purchase_data['Item ID'] == 178]['Item Name'].max()

In [122]:
#for each popular item, display name, purchase count, avg price, and total value
for i in range(len(items_sold)):
    print("Item ID: {} // Item Name: {} // Sold: {} // Price: ${} // Revenue ${}".format(
        items_sold.index[i],
        purchase_data.loc[purchase_data['Item ID'] == items_sold.index[i]]['Item Name'].max(),
        purchase_data.loc[purchase_data['Item ID'] == items_sold.index[i]]['Purchase ID'].count(),
        round(purchase_data.loc[purchase_data['Item ID'] == items_sold.index[i]]['Price'].mean(),2),
        round(purchase_data.loc[purchase_data['Item ID'] == items_sold.index[i]]['Price'].sum(),2)))

Item ID: 178 // Item Name: Oathbreaker, Last Hope of the Breaking Storm // Sold: 12 // Price: $4.23 // Revenue $50.76
Item ID: 82 // Item Name: Nirvana // Sold: 9 // Price: $4.9 // Revenue $44.1
Item ID: 108 // Item Name: Extraction, Quickblade Of Trembling Hands // Sold: 9 // Price: $3.53 // Revenue $31.77
Item ID: 145 // Item Name: Fiery Glass Crusader // Sold: 9 // Price: $4.58 // Revenue $41.22
Item ID: 92 // Item Name: Final Critic // Sold: 8 // Price: $4.88 // Revenue $39.04

## Most Profitable Items

* Sort the above table by total purchase value in descending order


* Optional: give the displayed data cleaner formatting


* Display a preview of the data frame

In [118]:
#most profitable items by total purchase value
profit_items = purchase_data.groupby('Item ID')['Price'].sum()
profit_items = profit_items.sort_values(ascending=False).head()
profit_items

Item ID
178    50.76
82     44.10
145    41.22
92     39.04
103    34.80
Name: Price, dtype: float64

In [123]:
#for each profitable item, display name, purchase count, avg price, and total value
for i in range(len(profit_items)):
    print("Item ID: {} // Item Name: {} // Sold: {} // Price: ${} // Revenue ${}".format(
        profit_items.index[i],
        purchase_data.loc[purchase_data['Item ID'] == profit_items.index[i]]['Item Name'].max(),
        purchase_data.loc[purchase_data['Item ID'] == profit_items.index[i]]['Purchase ID'].count(),
        round(purchase_data.loc[purchase_data['Item ID'] == profit_items.index[i]]['Price'].mean(),2),
        round(purchase_data.loc[purchase_data['Item ID'] == profit_items.index[i]]['Price'].sum(),2)))

Item ID: 178 // Item Name: Oathbreaker, Last Hope of the Breaking Storm // Sold: 12 // Price: $4.23 // Revenue $50.76
Item ID: 82 // Item Name: Nirvana // Sold: 9 // Price: $4.9 // Revenue $44.1
Item ID: 145 // Item Name: Fiery Glass Crusader // Sold: 9 // Price: $4.58 // Revenue $41.22
Item ID: 92 // Item Name: Final Critic // Sold: 8 // Price: $4.88 // Revenue $39.04
Item ID: 103 // Item Name: Singed Scalpel // Sold: 8 // Price: $4.35 // Revenue $34.8